### ISSUE TITLE
[BUG] Data loading error - wrong image resize

### ISSUE THREAD

**Issue by siavelis** [JiahuiYu/neuralgym#5] opened 2018-08-05 21:45 UTC
Hi Jiahui,

Opencv's expected shape is `(width,height)`.
The fix it's really easy, so, I'm submitting PR.

**Comment by JiahuiYu** [comment] 2018-08-05 22:43
Hi @siavelis, Thanks for your contribution! The problem is actually fixed in an internal version which will be released together with other updates soon.

**Closed by JiahuiYu** 2018-08-05 22:43 UTC
